### PR TITLE
fix: ethereumjs-abi ENOLOCAL error

### PR DESCRIPTION
**Pull request by drptbl**
changes:
- fixed `ethereumjs-abi` ENOLOCAL error (#650)
- reverted workaround (#652)

### CODE REVIEW

**Comment by drptbl** [comment]
Not sure why tests on CI has failed, seems like not related to my changes at all (probably flaky?).

**Comment by davidmurdoch** [comment]
Thanks @drptbl! Because of the way npm treats shrinkwraps*, this PR won't actually fix the issue once the package is published.

So, what i'm going to do for today is create a release with your fix by manually editing the shrinkwrap before it published to npm. I hope to upstream a fix this week so ganache no longer relies on this git package.

Thanks for this PR, btw... it really is saving me some extra headache! I close this issue once I'm finished with this manual release.

* if we publish the `npm-shrinkwrap.json` as is, when a user runs `npm install ganache-core` npm will install all of ganache's `devDependencies`, despite them being marked as `"dev": true` in the npm-shrinkwrap.json. So what we do on pre-publish is `npm prune --production` and then run `npm shrinkwrap` to recreate the shrinkwrap with only production dependencies. This restores the buggy `ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git` URL.

_note: I'm using npm v7 to maintain the shrinkwrap file due to another npm v6 bug that creates entries in the `npm-shrinkwrap.json` that omits package some urls... urls that npm will attempt to use on `npm install ganache-core`, which causes npm to just crash._

**Comment by davidmurdoch** [comment]
Update: this npm v7 issue is making it tricky to publish: https://github.com/npm/cli/issues/2045

**Comment by davidmurdoch** [comment]
I've published a beta and it looks like the fix works!

https://www.npmjs.com/package/ganache-core/v/2.13.1-beta.1

@drptbl, @alcuadrado do you mind installing this version out and letting me know if you have any issues?

**Comment by drptbl** [comment]
@davidmurdoch Indeed issues is fixed. Just tested. Thanks ;).

**Comment by davidmurdoch** [comment]
Fixed in 2.13.1 https://www.npmjs.com/package/ganache-core/v/2.13.1

**Pull request closed without merging**
