### PR TITLE
cleanup test properly for passing case

### PR DESCRIPTION
**Pull request by 0xNPE**
https://github.com/ethereumjs/merkle-patricia-tree/pull/28 looks like a promising fix for a part of the issue - 'get' of undefined

I've updated the test cases to clean up the error listener and pass properly when the issue is fixed

### CODE REVIEW

**Comment by benjamincburns** [comment]
Thanks, @0xNPE - I'll have a look at this with ethereumjs/merkle-patricia-tree#28 in the mix and see how it goes!

**Comment by benjamincburns** [comment]
Just commenting to say that I haven't forgotten this one - just waiting for a strong candidate for the open bounty until I merge it.

**Comment by seesemichaelj** [comment]
Blocked until the #453 is finished

**Comment by davidmurdoch** [comment]
@benjamincburns is this safe to merge now that https://github.com/trufflesuite/ganache-core/pull/209 is merged?

**Comment by davidmurdoch** [comment]
Closing as these tests require significant refactoring at this point due to underlying vm changes.

**Pull request closed without merging**
