### PR TITLE
chore: bump ethereumjs-util, ethereumjs-wallet, web3, and websocket deps

### PR DESCRIPTION
**Pull request by nebojsa94**
This PR removes the need to compile with node-gyp :rocket:

Install stats (via github)
This PR: `35.099s`
Current develop: `94.833s`

### CODE REVIEW

**Comment by alcuadrado** [comment]
Hey @gnidan, @davidmurdoch 

This PR and https://github.com/trufflesuite/ganache-cli/pull/770 are some the last few things needed to completely node-gyp from the entire ecosystem. 

Can you take a look at them?

Thanks!

**Comment by nebojsa94** [comment]
Hey @davidmurdoch @seesemichaelj 

I've resolved the conflicts here and in https://github.com/trufflesuite/ganache-cli/pull/770. Can you take a look?

Cheers!

**Review by seesemichaelj — COMMENTED** [review]
Generally these changes look good to me, but I defer to @davidmurdoch on this one

**Comment by rekmarks** [comment]
Merging this would be greatly appreciated since it also resolves `websocket`-related security vulnerabilities that currently have to be resolved manually by `ganache-core` consumers.

**Comment by davidmurdoch** [comment]
Thanks @nebojsa94!

**Pull request merged**
