### PR TITLE
upgrade ethereumjs-vm to 2.3.1 (Byzantium)

### PR DESCRIPTION
**Pull request by jwasinger**
This PR upgrades ganache-core to be compatible with the Byzantium release.

### CODE REVIEW

**Comment by jwasinger** [comment]
This is blocked until develop is merged into master.

**Comment by jwasinger** [comment]
Ah this introduces two failing tests.

**Comment by benjamincburns** [comment]
@jwasinger we moved this over to be based on the `develop` branch, as we'll likely merge it there first (`master` is the current release). It looks like the only tests failing are due to the `stateRoot` hash having changed, which given that no other tests failed and that the VM was updated, this is to be expected. I'm happy to accept this PR as-is, and I'll update the tests accordingly.

**Comment by jwasinger** [comment]
Thanks @benjamincburns don't hesitate to reach out to me if anything broken appears as a result of this

**Pull request merged**
