### PR TITLE
fix attempt for issue #339

### PR DESCRIPTION
**Pull request by iccicci**
Hi all,

probably there are thousands of better ways to fix this issue, but at least this will allow to use web3.js version 1.0.0-beta.47 or higher.

Hope this helps,
iCC

### CODE REVIEW

**Comment by iccicci** [comment]
Hi @davidmurdoch ,

can you please give me some feedback about this task?
Is there something else I should do? IS there a documentation I have to read in order to do a _good_ PR?

Thank you,
iCC

**Comment by iccicci** [comment]
Thank you for appreciating my job @davidmurdoch ;

unfortunately the problem is not my bandwidth, it is my knowledge; it seems I have to study a lot in order to be able to answer to all your question/investigations. :(
I'll try to learn something, but feel free to go on with this topic on some different way.

By the way, if I try to run all tests on my local machine (I use WSL) many of them fails; I can see there is a docker file, can you please explain me how to run tests locally?

Thank you,
iCC

**Comment by davidmurdoch** [comment]
@iccicci, All you need to do is run `npm test` (after `npm install`) and you all tests should pass. I _think_ I recall seeing timeouts when running the tests under wsl due to the tests timing out, as wsl can be a little slow. You can develop on ganache-core in windows, including running the tests. Give it a shot and let me know if you have any problems running it.

**Comment by iccicci** [comment]
@davidmurdoch ,

I paid a bit more attention to error messages; upgraded node.js from v9 to v10; increased timeout in Gas tests; now all tests pass.

Thank you!

**Pull request closed without merging**
