### PR TITLE
Preserve transaction signatures.

### LINKED ISSUE #56: Transaction Hashes are Computed Incorrectly
ganache-core uses EIP-155 hashes to identify transactions. This causes JSON-RPC calls like `eth_sendRawTransaction` to return unexpected values. The EIP-155 hash should be used to generate a signature. It should not be used to identify the transaction in the RPC mechanism. 

## Expected Behavior
```bash
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86b808504e3b2920082520894a3bd45f7b000a6d3d2359b0577ed34adbdfc25eb87038d7ea4c68000802aa0dec7e8ff13c93cdc9a75432f01730bdc3a20fc0eaf820a7234c1aabdbf6ccb64a0601845af5cbd02e9c443f870bdbee61c93a5533c4c3f84931a0e1dfab30d39ab"],"id":1}' https://ropsten.infura.io
{"jsonrpc":"2.0","id":1,"result":"0xe1ba8a320f9fc6846127b244faf9825028d7298c4d34c4aa0fc57d48b85a7ab3"}
```

## Current Behavior
```bash
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86b808504e3b2920082520894a3bd45f7b000a6d3d2359b0577ed34adbdfc25eb87038d7ea4c68000802aa0dec7e8ff13c93cdc9a75432f01730bdc3a20fc0eaf820a7234c1aabdbf6ccb64a0601845af5cbd02e9c443f870bdbee61c93a5533c4c3f84931a0e1dfab30d39ab"],"id":1}' localhost:8545
{"id":1,"jsonrpc":"2.0","result":"0x56860ff2721668edd33f5f86abdbd44fe1a8e8f3efba1a12dc76f2c9da53b836"}
```
Notice that the hash is `0x56860ff2721668edd33f5f86abdbd44fe1a8e8f3efba1a12dc76f2c9da53b836` instead of `sha3(data) = 0xe1ba8a320f9fc6846127b244faf9825028d7298c4d34c4aa0fc57d48b85a7ab3`

## Possible Solution
Always use `sha3(rawData)` to identify signed transactions, including over json rpc.

## Steps to Reproduce (for bugs)
Run gananche-cli in the background using this:

```javascript
const secretKey = Buffer.from('8874F01D72E7BE5D5417B55E0F21698692704F408C1AFF382641DB0423F1B2E1', "hex");
const config = {
  "accounts": [
    { "balance": 1000000 * 1000000000000000000,
      "secretKey": secretKey
    }, ], };

require("ganache-cli").server(config).listen(8545);
```

Then run curl as above.

## Context
Transaction hashes computed outside of ganache-core/ganache-cli do not match those expected or returned by ganache-X. This makes it difficult to use ganache-X for testing applications that interact with other Ethereum nodes.

## Your Environment
* Version used: Ganache CLI v7.0.0-beta.0 (ganache-core: 3.0.0-beta.0)
* Operating System and version: macOS 10.13.2

### PR DESCRIPTION
**Pull request by mgraczyk**
This fixes transaction hashes being computed incorrectly for signed messages submitted via eth_sendRawTransaction.

This should fix #56 .

### CODE REVIEW

**Comment by mgraczyk** [comment]
@benjamincburns Thoughts on merging?

**Comment by benjamincburns** [comment]
Hi @mgraczyk - thanks for pinging me - I'd meant to respond sooner.

I haven't had a chance to give this a try yet, however if you could add some tests for the functionality that'll make it much simpler to evaluate.

**Comment by mgraczyk** [comment]
@benjamincburns I added a test which fails before and passes after the change.

**Comment by benjamincburns** [comment]
LGTM - thanks for the contribution, @mgraczyk!

**Pull request merged**
