### PR TITLE
feat(tezos): update to delphi protocol

### PR DESCRIPTION
**Pull request by shekhar-shubhendu**
This PR does the following:
- ~aligns `tezos` branch to latest master~
- add updates required for delphinet protocol update

depends on https://github.com/trufflesuite/flextesa-mini-archive/pull/2

### CODE REVIEW

**Comment by shekhar-shubhendu** [comment]
Once a new version of `@truffle/contract` is released that contains changes from https://github.com/trufflesuite/truffle/pull/3510 then we should update the version of `@truffle/contract` here too

**Comment by davidmurdoch** [comment]
Thanks for this PR, @shekhar-shubhendu! Can you rebase this off our tezos branch (or otherwise remove the merge from master?) so it contains only your changes?

**Comment by shekhar-shubhendu** [comment]
@davidmurdoch sure will do now.

**Comment by shekhar-shubhendu** [comment]
Thanks again @davidmurdoch for accepting the PR. 🙏

**Pull request merged**
